name: Kang Rekon
title: null
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [The Rekons]
description: [Informasi Seputar Bansos PPKH Kab. Kuningan]
show_downloads: false
